### ISSUE TITLE
rn

### ISSUE THREAD

**Issue by semihagungor** [ivanbtrujillo/SuperHero-RN-Curso#2]
hi, I am workin android from windows. I am usin react native v 0.47.1 I have a problem SuperHero "Super expression must either be null or a function, not undefined".
Change my import statement
 import React, { Component } from 'react';
 import {
   AppRegistry,
   StyleSheet,
   Text,
   Navigator,
   TouchableHighlight
 } from 'react-native';

but dont working. can you please help me.

**Comment by ivanbtrujillo** [comment]
It seems to be a problem in your class definition. Make sure that your class is extending Component and your constructor is defined as:
```
class YourName extends Component{
  constructor (props){
     super(props)
  } 
  // other things here
}
```
Also, if you give me the name of the file that is giving you the error and the code of that file, i could give you a more precise response.

Note that this project is not updated to the latest version of React Native. This is just a code for a course that i did a year ago, is not a mantained project.

Regards
